import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('paldawn:settings:v1', JSON.stringify({
    version: 1, state: { textVoyagePreferred: true, reducedMotion: true },
  })))
})

for (const width of [320, 375, 1280]) {
  test(`focused reading contains keyboard interaction and restores its opener at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('./#atlas/diabetes/pancreas-senses')
    const route = page.url()
    const opener = page.getByRole('button', { name: 'Compare pathway' })
    await opener.click()
    const reader = page.getByRole('dialog', { name: 'Diabetes mellitus' })
    const close = reader.getByRole('button', { name: 'Close focused reading' })
    const lastSource = reader.getByRole('link').last()
    await expect(close).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(lastSource).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(close).toBeFocused()

    // Global journey shortcuts must not operate behind the modal.
    await page.keyboard.press('ArrowRight')
    await page.keyboard.press('t')
    expect(page.url()).toBe(route)
    await expect(page.locator('.drawer')).toHaveCount(0)
    await page.keyboard.press('Escape')
    await expect(reader).toHaveCount(0)
    expect(page.url()).toBe(route)
    await expect(opener).toBeFocused()

    await opener.click()
    await close.click()
    await expect(opener).toBeFocused()
    await opener.click()
    await reader.getByRole('button', { name: 'Open in systems map' }).first().click()
    await expect(reader).toHaveCount(0)
    await expect(page.getByRole('heading', { name: 'Food enters the digestive tract', exact: true })).toBeVisible()
    await expect(opener).toBeFocused()
  })
}

test('focused reader prints authored content and includes notes only when selected', async ({ page }, testInfo) => {
  await page.goto('./#atlas/diabetes/pancreas-senses')
  await page.getByRole('button', { name: 'Private note', exact: true }).click()
  await page.getByLabel(/Private note · stored only in this browser/).fill('Fictional print privacy check')
  await page.getByRole('button', { name: 'Compare pathway' }).click()
  const reader = page.getByRole('dialog', { name: 'Diabetes mellitus' })
  await page.emulateMedia({ media: 'print' })
  await expect(reader.getByRole('heading', { name: 'The pancreas releases insulin', exact: true })).toBeVisible()
  await expect(reader.getByRole('heading', { name: 'Plain English' }).first()).toBeVisible()
  await expect(reader.getByRole('heading', { name: 'Clinical terms' }).first()).toBeVisible()
  await expect(reader.getByRole('link').first()).toBeVisible()
  await expect(reader.locator('.atlas-caution').first()).toHaveCSS('color', 'rgb(0, 0, 0)')
  await expect(page.getByText('Fictional print privacy check', { exact: true })).not.toBeVisible()
  await expect(page.locator('.masthead')).not.toBeVisible()
  await expect(page.locator('.atlas-detail')).not.toBeVisible()
  await expect(reader.getByRole('button', { name: 'Open in systems map' }).first()).not.toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('reader-print.png'), fullPage: true })
  await page.emulateMedia({ media: 'screen' })
  await reader.getByRole('checkbox', { name: 'Show private notes and include in export' }).check()
  await page.emulateMedia({ media: 'print' })
  await expect(reader.getByText('Fictional print privacy check', { exact: true })).toBeVisible()
})

test('First Light transcript prints its text without background or navigation controls', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('./')
  await page.getByRole('button', { name: 'Transcript', exact: true }).click()
  await page.emulateMedia({ media: 'print' })
  const printedLayout = await page.locator('.drawer').evaluate((drawer) => {
    const bounds = drawer.getBoundingClientRect()
    return { left: bounds.left, right: bounds.right, pageWidth: document.documentElement.scrollWidth, viewportWidth: window.innerWidth }
  })
  expect(printedLayout.left).toBeGreaterThanOrEqual(0)
  expect(printedLayout.right).toBeLessThanOrEqual(printedLayout.viewportWidth)
  expect(printedLayout.pageWidth).toBe(printedLayout.viewportWidth)
  await expect(page.getByRole('heading', { name: 'Full transcript', exact: true })).toBeVisible()
  await expect(page.locator('.transcript-list > li')).toHaveCount(5)
  await expect(page.locator('.transcript-list p').first()).toBeVisible()
  await expect(page.locator('.transcript-list p').last()).toBeVisible()
  await expect(page.locator('.intro')).not.toBeVisible()
  await expect(page.locator('.masthead')).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Go to stage' }).first()).not.toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('transcript-print.png'), fullPage: true })
})

test('Study Desk prints selected records with an explicit note opt-in', async ({ page }, testInfo) => {
  await page.goto('./#atlas/diabetes/pancreas-senses')
  await page.getByRole('button', { name: 'Save step', exact: true }).click()
  await page.getByRole('button', { name: 'Private note', exact: true }).click()
  await page.getByLabel(/Private note · stored only in this browser/).fill('Fictional desk privacy check')
  await page.getByRole('button', { name: /Back to overview/ }).click()
  await page.getByRole('button', { name: 'Atlas desk', exact: true }).click()
  const desk = page.getByRole('dialog', { name: 'Your Atlas study desk' })
  await page.emulateMedia({ media: 'print' })
  await expect(desk.getByRole('heading', { name: 'The pancreas releases insulin', exact: true })).toBeVisible()
  await expect(desk.getByText('Fictional desk privacy check', { exact: true })).not.toBeVisible()
  await expect(page.locator('.intro')).not.toBeVisible()
  await expect(desk.getByRole('button', { name: 'Open exact step' })).not.toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('desk-print.png'), fullPage: true })
  await page.emulateMedia({ media: 'screen' })
  await desk.getByRole('checkbox', { name: 'Include private notes in download and print' }).check()
  await page.emulateMedia({ media: 'print' })
  await expect(desk.getByText('Fictional desk privacy check', { exact: true })).toBeVisible()
})
