import { lazy, Suspense, useEffect, useState } from 'react'
import type { Atlas } from './anatomy'
import { DEFAULT_VISIBLE } from './anatomy'
import { useSettings } from '../state/settings'
import './landing.css'
import researchPreview from '../../../docs/assets/paldawn-research-desk.png'
import catalog from './researchCatalog.json'
const featuredTracks = catalog.tracks.filter(track => ['heart', 'kidneys', 'brain'].includes(track.id))
const Scene = lazy(() => import('./scene'))
export default function AnatomyLanding({ onExplore, onJourneys }: { onExplore: (sex: 'male' | 'female') => void; onJourneys: () => void }) {
  const [sex, setSex] = useState<'male' | 'female'>('female')
  const [rotating, setRotating] = useState(true)
  const [atlas, setAtlas] = useState<Atlas | null>(null)
  const [error, setError] = useState('')
  const [progress, setProgress] = useState(0)
  const reducedMotion = useSettings(s => s.reducedMotion)
  useEffect(() => {
    const abort = new AbortController(); setAtlas(null); setError(''); setProgress(0)
    fetch(`${import.meta.env.BASE_URL}anatomy/models/${sex === 'female' ? 'atlas-female.json' : 'atlas.json'}`, { signal: abort.signal }).then(r => { if (!r.ok) throw new Error('Reference preview unavailable. Open the lab to retry or study in text.'); return r.json() }).then(data => { if (!abort.signal.aborted) setAtlas(data) }).catch(e => { if (!abort.signal.aborted) setError(e.message) })
    return () => abort.abort()
  }, [sex])
  return <main className="anatomy-landing">
    <header className="anatomy-site-nav"><a href="#top" className="anatomy-site-brand"><img src={`${import.meta.env.BASE_URL}icon-static.svg`} alt=""/>PalDawn</a><nav aria-label="Website"><a href="#learning">The study experience</a><a href="#research">Research desk</a><a href="#references">Our references</a><button onClick={() => onExplore(sex)}>Enter the lab ↗</button></nav></header>
    <section id="top" className="anatomy-hero"><div className="anatomy-hero-copy"><p className="site-eyebrow">ANATOMY, WITH CONNECTIONS.</p><h1>A body is more<br/>than its <em>parts.</em></h1><p className="site-lede">Learn the structure. See its place in the system. Investigate how it works and what changes in disease. A visual study companion for the questions that make medicine fascinating.</p><div className="site-actions"><button className="site-primary" onClick={() => onExplore(sex)}>Explore Anatomy Lab <span>↗</span></button><button onClick={onJourneys}>Follow a disease pathway</button></div><p className="site-candidate">Local preview · Anatomy and clinical review pending</p><div className="site-reference-caption"><span>{sex === 'female' ? 'HRA / FEMALE REFERENCE ASSEMBLY' : 'BODYPARTS3D / ADULT MALE REFERENCE'}</span><p>{sex === 'female' ? '888 selectable meshes. Female reproductive structures included. Skeleton and muscle coverage are partial.' : '2,234 selectable meshes across 15 display systems. An adult reference, not every human variation.'}</p></div></div>
      <div className="anatomy-hero-stage"><div className="site-model-switch" role="group" aria-label="Preview reference"><button aria-pressed={sex === 'female'} onClick={() => setSex('female')}>Female</button><button aria-pressed={sex === 'male'} onClick={() => setSex('male')}>Male</button><button disabled={reducedMotion} onClick={() => setRotating(v => !v)}>{rotating && !reducedMotion ? 'Pause' : 'Rotate'}</button></div>
        {atlas && !error ? <Suspense fallback={null}><Scene atlas={atlas} state={{ visible: [...DEFAULT_VISIBLE, ...(sex === 'female' ? ['integumentary' as const] : [])], selected: [], explode: 0, isolate: false, view: 'three-quarter', rotate: rotating && !reducedMotion, reducedMotion, reset: 0, quality: 'high', presentation: true }} onSelect={() => onExplore(sex)} onProgress={setProgress} onError={setError}/></Suspense> : null}
        {error ? <p className="site-model-status">{error}</p> : progress < 100 ? <p className="site-model-status">Preparing reference anatomy · {progress}%</p> : null}<div className="site-model-caption"><span>LIVE REFERENCE / DRAG TO EXPLORE</span><p>Real source meshes. A new perspective with every turn.</p></div>
      </div></section>
    <section id="learning" className="anatomy-learning"><div><p className="site-eyebrow">FROM IDENTIFICATION TO UNDERSTANDING</p><h2>Stay curious.<br/>Go one layer deeper.</h2></div><div className="anatomy-learning-steps"><article><span>STRUCTURE</span><h3>Take the body apart.</h3><p>Search names and source identifiers, isolate a structure, then separate the reference into an inventory of individual pieces.</p></article><article><span>RELATIONSHIP</span><h3>Keep the context.</h3><p>Switch system layers, take a guided tour, or follow an organ-level connection into an existing PalDawn disease pathway.</p></article><article><span>RESEARCH</span><h3>Follow your own question.</h3><p>Explore 20 body-area tracks, function questions and 113 condition topics. Save a reading queue, find review literature, and export your study plan.</p></article></div></section>
    <section id="research" className="anatomy-research-story" aria-labelledby="research-story-title">
      <div className="research-story-heading"><p className="site-eyebrow">YOUR NEXT QUESTION STARTS HERE</p><h2 id="research-story-title">From a structure<br/>to a line of inquiry.</h2><p>Start with normal function. Explore what changes in disease. Keep the questions you want to follow, with the sources close at hand.</p></div>
      <div className="research-story-questions">{featuredTracks.map(track => <article key={track.id}><span>{track.title}</span><h3>{track.function.title}</h3><p>{track.prompt}</p><a href={track.function.url} target="_blank" rel="noreferrer">Read the {track.function.publisher} introduction ↗</a></article>)}</div>
      <figure className="research-story-proof"><img src={researchPreview} width="1440" height="900" loading="lazy" alt="Local Anatomy Lab research desk beside the reference model, showing a function question and source reading controls"/><figcaption>Actual local preview. Choose a reading area, open a source, and save a question. Reading links and searches are starting points, not appraised evidence or new disease simulations.</figcaption></figure>
      <div className="research-story-control"><div><h3>A reading plan that belongs to you.</h3><p>Search 113 condition topics across 20 areas. Choose compact cards or a wider research view, save selected topics, then export Markdown. The queue stays in this session and resets on reload.</p></div><button className="site-primary" onClick={() => onExplore(sex)}>Build a reading plan ↗</button></div>
    </section>
    <section id="references" className="anatomy-references"><div><p className="site-eyebrow">A REFERENCE IS A STARTING POINT.</p><h2>Two sources.<br/>Clearly stated limits.</h2><p>These assemblies show different sets of structures. They are not a matched pair, complete human anatomy, or a substitute for a validated medical curriculum.</p></div><div className="site-reference-table"><article><span>ADULT MALE</span><h3>BodyParts3D 4.0</h3><p>2,234 meshes · 3,432 named concepts</p><p>Broad system coverage from an adult male reference. Individual variation and developmental stages are outside its scope.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/" target="_blank" rel="noreferrer">Explore the source ↗</a></article><article><span>FEMALE ASSEMBLY</span><h3>Human Reference Atlas</h3><p>888 meshes · 1,073 source nodes</p><p>Female reproductive anatomy and selected organs, with partial skeleton and muscles. Optional pregnancy reference structures are separate from the default view.</p><a href="https://lod.humanatlas.io/ref-organ/united-female/v1.5/" target="_blank" rel="noreferrer">Explore the source ↗</a></article></div></section>
    <section className="anatomy-site-help" aria-labelledby="study-help-title"><div><p className="site-eyebrow">A LITTLE ORIENTATION</p><h2 id="study-help-title">Start with curiosity.<br/>Keep the limits in view.</h2></div><div><p>This local preview is for exploration. Sources and source meshes do not establish clinical accuracy. Named qualified anatomy and clinical review is pending.</p><p>No account is required. Study queues stay in memory; opening a source or PubMed link contacts that external website. Export your plan before closing.</p><nav aria-label="Study help"><a href="https://github.com/udhawan97/PalDawn/blob/main/docs/GETTING-STARTED.md" target="_blank" rel="noreferrer">Study guide ↗</a><a href="https://github.com/udhawan97/PalDawn/blob/main/docs/ANATOMY-LAB.md" target="_blank" rel="noreferrer">Local setup ↗</a><a href="https://github.com/udhawan97/PalDawn/issues" target="_blank" rel="noreferrer">Report a problem ↗</a></nav></div></section>
    <footer className="anatomy-site-footer"><p>Made for learning. Not diagnosis, treatment, or clinical decision-making.</p><p>Viewer adapted from <a href="https://github.com/ashemag/human-atlas">Human Atlas by ashemag</a>, MIT. Anatomy: BodyParts3D / Database Center for Life Science and Kristen Browne & Heidi Schlehlein / HRA, CC BY 4.0. <a href={`${import.meta.env.BASE_URL}anatomy/ATTRIBUTION.md`}>Full credits</a>.</p><span>PALDAWN · ANATOMY LAB / LOCAL CANDIDATE</span></footer>
  </main>
}
